
export const genres = [
    { label: "Action", value: "28" },
    { label: "Adventure", value: "12" },
    { label: "Animation", value: "16"},
    { label: "Comedy", value: "35"},
    { label: "Crime", value: "80"},
    { label: "Documentary", value: "99"},
    { label: "Drama", value: "18"},
    { label: "Family", value: "10751"},
    { label: "History", value: "36"},
    { label: "Horror", value: "27"},
    { label: "Music", value: "10402"},
    { label: "Mystery", value: "9648"},
    { label: "Romance", value: "10749"},
    { label: "Sci-Fi", value: "878"},
    { label: "Thriller", value: "53"},
    { label: "War", value: "10752"},
    { label: "Western", value: "37"},

]

export const languages = [
    { label: "Arabic", value: "ar" },
    { label: "Chinese", value: "zh" },
    { label: "Czech", value: "cs" },
    { label: "Danish", value: "da" },
    { label: "Dutch", value: "nl" },
    { label: "English", value: "en" },
    { label: "Finnish", value: "fi" },
    { label: "French", value: "fr" },
    { label: "German", value: "de" },
    { label: "Greek", value: "el" },
    { label: "Hebrew", value: "he" },
    { label: "Hindi", value: "hi" },
    { label: "Hungarian", value: "hu" },
    { label: "Icelandic", value: "is" },
    { label: "Indonesian", value: "id" },
    { label: "Italian", value: "it" },
    { label: "Japanese", value: "ja" },
    { label: "Korean", value: "ko" },
    { label: "Norwegian", value: "no" },
    { label: "Polish", value: "pl" },
    { label: "Porteguese", value: "pt" },
    { label: "Romanian", value: "ro" },
    { label: "Russian", value: "ru" },
    { label: "Spanish", value: "es" },
    { label: "Swahili", value: "sw" },
    { label: "Swedish", value: "sv" },
    { label: "Thai", value: "th" },
    { label: "Turkish", value: "tr" },
    { label: "Vietnamese", value: "vi" },
]

export const age = [
    { label: "For kids", value: "kid" },
    { label: "Mature (+18)", value: "adult" },
]