
export const genres = [
    { label: "Action", value: "28" },
    { label: "Adventure", value: "12" },
    { label: "Animation", value: "16"},
    { label: "Comedy", value: "35"},
    { label: "Crime", value: "80"},
    { label: "Documentary", value: "99"},
    { label: "Drama", value: "18"},
    { label: "Family", value: "10751"},
    { label: "History", value: "36"},
    { label: "Horror", value: "27"},
    { label: "Music", value: "10402"},
    { label: "Mystery", value: "9648"},
    { label: "Romance", value: "10749"},
    { label: "Sci-Fi", value: "878"},
    { label: "Thriller", value: "53"},
    { label: "War", value: "10752"},
    { label: "Western", value: "37"},

]

export const languages = [
    { label: "Arabic", value: "ar-SA" },
    { label: "Chinese", value: "zh-CN" },
    { label: "Czech", value: "cs-CZ" },
    { label: "Danish", value: "da-DK" },
    { label: "Dutch", value: "nl-NL" },
    { label: "English", value: "en-US" },
    { label: "Finnish", value: "fi-FI" },
    { label: "French", value: "fr-CA" },
    { label: "German", value: "de-DE" },
    { label: "Greek", value: "el-GR" },
    { label: "Hebrew", value: "he-IL" },
    { label: "Hindi", value: "hi-IN" },
    { label: "Hungarian", value: "hu-HU" },
    { label: "Indonesian", value: "id-ID" },
    { label: "Italian", value: "it-IT" },
    { label: "Japanese", value: "ja-JP" },
    { label: "Korean", value: "ko-KR" },
    { label: "Norwegian", value: "no-NO" },
    { label: "Polish", value: "pl-PL" },
    { label: "Porteguese", value: "pt-PT" },
    { label: "Romanian", value: "ro-RO" },
    { label: "Russian", value: "ru-RU" },
    { label: "Spanish", value: "es-ES" },
    { label: "Swedish", value: "sv-SE" },
    { label: "Thai", value: "th-TH" },
    { label: "Turkish", value: "tr-TR" },
    { label: "Vietnamese", value: "vi-VN" },
]

export const age = [
    { label: "For kids", value: "kid" },
    { label: "All", value: "adult" },
]